### ISSUE TITLE
Unable to open up main.tscn

### ISSUE THREAD

**Issue by mathew-tran** [tm-nielsen/Golfo#1]
Repro steps:
- Clone project
- Open up on Godot 4.1.2
- Attempt to open up main.tscn
- Get Error
![image](https://github.com/tm-nielsen/Golfo/assets/26263343/d733250e-6575-4173-a3f3-c3e145eeefdc)

**Comment by mathew-tran** [comment]
Looking to get into an open source godot project! Once I can get the game is up and running. I'll take more of a look and try to make some contributions :)
Cheers

**Comment by tm-nielsen** [comment]
I appreciate the interest, but this isn't an open source project.

I'm happy to answer any questions about how I've made things if you're looking to learn, that's the main reason the repository is public. Make sure to keep track of licenses when sourcing from or contributing to projects online 🙂

Your issue is likely caused by the direct import of multiple .blend files, which requires a path to a Blender 3 installation:
Editor -> Editor Settings -> File System -> Import -> Blender 3 Path.

Let me know if you have any questions, I hope you find what you're looking for!
